#!/usr/bin/python
import fnmatch
import os
import glob
dirPath=/root/my_new_project/GLOB
pattern=".txt"
  
'''
Generic function to delete all the files from a given directory based on matching pattern
'''
def removeFilesByMatchingPattern(dirPath, pattern):
    listOfFilesWithError = []
    for parentDir, dirnames, filenames in os.walk(dirPath):
        for filename in fnmatch.filter(filenames, pattern):
            try:
                os.remove(os.path.join(parentDir, filename))
            except:
                print("Error while deleting file : ", os.path.join(parentDir, filename))
                listOfFilesWithError.append(os.path.join(parentDir, filename))
                
 
    return listOfFilesWithError
if __name__ == "__main__":
    removeFilesByMatchingPattern('/root/my_new_project/GLOB/','*.txt')

    

      
