#!/usr/bin/python
import os
import socket


def retBanner(ip, port):
    socket.setdefaulttimeout(2)
    s = socket.socket()
    s.connect((ip, port))
    banner = s.recv(1024)
    print(ip + "is UP")
    return banner

def retport(ip,port):
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex((ip, port))
        if result == 0:
            print("port {} ,is open {}: ".format(port,ip))
        else:
            print("port {} is closed {}:".format(port,ip))
    except BaseException as ex:
        print(ex)



def main():
    portlist = [22]
    for x in range(130, 132):
        for port in portlist:
            ip_address = '192.168.118.' + str(x)
            retBanner(ip_address, port)
            retport(ip_address,port)


if __name__ == '__main__':
    main()
